# Generated by Django 6.0.3 on 2026-10-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('calories', models.FloatField()),
                ('proteins', models.FloatField()),
                ('fat', models.FloatField()),
                ('carbohydrate', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, default='', max_length=1000)),
                ('name_normalized', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'db_table': 'nutrition',
                'ordering': ['id'],
            },
        ),
    ]
